# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/centos7-docker"
  config.vm.network "forwarded_port", guest: 80, host: 8081 
  config.vm.synced_folder ".", "/vagrant"


end
